version: '3.8'

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: yourdb
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_NAME: yourdb
      JWT_SECRET: supersecretkey
    volumes:
      - .:/app
    command: npm run dev # หรือ "node server.js" ถ้าไม่มี nodemon

volumes:
  db-data:
